# Generated by Django 3.2.9 on 2021-11-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Policy_id', models.IntegerField(max_length=255, unique=True)),
                ('Date_of_Purchase', models.DateField()),
                ('Customer_id', models.IntegerField(max_length=255)),
                ('Fuel', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('VEHICLE_SEGMENT', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('Premium', models.IntegerField(max_length=255, unique=True)),
                ('Bodily_injury_liability', models.BooleanField(default=False)),
                ('Personal_injury_protection', models.BooleanField(default=False)),
                ('Property_damage_liability', models.BooleanField(default=False)),
                ('Collision', models.BooleanField(default=False)),
                ('Comprehensive', models.BooleanField(default=False)),
                ('Customer_Marital_status', models.BooleanField(default=False)),
                ('Customer_Gender', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Customer_Income_Group', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Customer_Region', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
