# Generated by Django 3.2.9 on 2021-11-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcessedRecord', '0003_alter_processedrecord_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedrecord',
            name='Customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='processedrecord',
            name='Premium',
            field=models.IntegerField(null=True),
        ),
    ]
